// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RHESSYs_Data_Importer.DAL;

#nullable disable

namespace RHESSYs_Data_Importer.Migrations.CentralCoastV3
{
    [DbContext(typeof(CentralCoastV3DbContext))]
    partial class CentralCoastV3DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoastV3.CubeDataRowV3", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("Qin")
                        .HasColumnType("float");

                    b.Property<float>("Qout")
                        .HasColumnType("float");

                    b.Property<int>("basinID")
                        .HasColumnType("int");

                    b.Property<float>("burn")
                        .HasColumnType("float");

                    b.Property<float>("canopyevap")
                        .HasColumnType("float");

                    b.Property<float>("coverfract")
                        .HasColumnType("float");

                    b.Property<int>("dateIdx")
                        .HasColumnType("int");

                    b.Property<float>("depthToGW")
                        .HasColumnType("float");

                    b.Property<float>("fire")
                        .HasColumnType("float");

                    b.Property<float>("gppOver")
                        .HasColumnType("float");

                    b.Property<float>("gppUnder")
                        .HasColumnType("float");

                    b.Property<float>("groundevap")
                        .HasColumnType("float");

                    b.Property<float>("heightOver")
                        .HasColumnType("float");

                    b.Property<float>("heightUnder")
                        .HasColumnType("float");

                    b.Property<int>("importRunId")
                        .HasColumnType("int");

                    b.Property<float>("laiOver")
                        .HasColumnType("float");

                    b.Property<float>("laiUnder")
                        .HasColumnType("float");

                    b.Property<float>("leafCOver")
                        .HasColumnType("float");

                    b.Property<float>("leafCUnder")
                        .HasColumnType("float");

                    b.Property<float>("litterc")
                        .HasColumnType("float");

                    b.Property<float>("netpsnOver")
                        .HasColumnType("float");

                    b.Property<float>("netpsnUnder")
                        .HasColumnType("float");

                    b.Property<long>("patchID")
                        .HasColumnType("bigint");

                    b.Property<float>("rain")
                        .HasColumnType("float");

                    b.Property<float>("relHumidity")
                        .HasColumnType("float");

                    b.Property<float>("respOver")
                        .HasColumnType("float");

                    b.Property<float>("respUnder")
                        .HasColumnType("float");

                    b.Property<float>("rootCOver")
                        .HasColumnType("float");

                    b.Property<float>("rootCUnder")
                        .HasColumnType("float");

                    b.Property<float>("rootdepth")
                        .HasColumnType("float");

                    b.Property<float>("rootdepthCOver")
                        .HasColumnType("float");

                    b.Property<float>("rootdepthUnder")
                        .HasColumnType("float");

                    b.Property<int>("scenarioIdx")
                        .HasColumnType("int");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float>("soilc")
                        .HasColumnType("float");

                    b.Property<float>("stemCOver")
                        .HasColumnType("float");

                    b.Property<float>("streamflow")
                        .HasColumnType("float");

                    b.Property<float>("tmax")
                        .HasColumnType("float");

                    b.Property<float>("tmin")
                        .HasColumnType("float");

                    b.Property<float>("transOver")
                        .HasColumnType("float");

                    b.Property<float>("transUnder")
                        .HasColumnType("float");

                    b.Property<float>("vegAccessWater")
                        .HasColumnType("float");

                    b.Property<float>("windDirection")
                        .HasColumnType("float");

                    b.Property<float>("windSpeed")
                        .HasColumnType("float");

                    b.Property<int>("zoneID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scenarioRunId", "scenarioIdx", "dateIdx", "zoneID", "patchID");

                    b.ToTable("CubeData");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.Date", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Dates");
                });
#pragma warning restore 612, 618
        }
    }
}
