// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RHESSYs_Data_Importer.DAL;


#nullable disable

namespace RHESSYs_Data_Importer.Migrations
{
    [DbContext(typeof(CubeDataDbContext))]
    [Migration("20240818190208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CubeDataPoint", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("Qout")
                        .HasColumnType("float");

                    b.Property<int>("dateIdx")
                        .HasColumnType("int");

                    b.Property<float>("depthToGW")
                        .HasColumnType("float");

                    b.Property<float>("evap")
                        .HasColumnType("float");

                    b.Property<float>("heightOver")
                        .HasColumnType("float");

                    b.Property<float>("heightUnder")
                        .HasColumnType("float");

                    b.Property<float>("leafCOver")
                        .HasColumnType("float");

                    b.Property<float>("leafCUnder")
                        .HasColumnType("float");

                    b.Property<float>("litter")
                        .HasColumnType("float");

                    b.Property<float>("netpsn")
                        .HasColumnType("float");

                    b.Property<int>("patchIdx")
                        .HasColumnType("int");

                    b.Property<float>("rootCOver")
                        .HasColumnType("float");

                    b.Property<float>("rootCUnder")
                        .HasColumnType("float");

                    b.Property<float>("snow")
                        .HasColumnType("float");

                    b.Property<float>("soil")
                        .HasColumnType("float");

                    b.Property<float>("stemCOver")
                        .HasColumnType("float");

                    b.Property<float>("stemCUnder")
                        .HasColumnType("float");

                    b.Property<float>("transOver")
                        .HasColumnType("float");

                    b.Property<float>("transUnder")
                        .HasColumnType("float");

                    b.Property<float>("vegAccessWater")
                        .HasColumnType("float");

                    b.Property<int>("warmingIdx")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CubeData");
                });
#pragma warning restore 612, 618
        }
    }
}
