// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RHESSYs_Data_Importer.DAL;

#nullable disable

namespace RHESSYs_Data_Importer.Migrations.CentralCoast
{
    [DbContext(typeof(CentralCoastDbContext))]
    partial class CentralCoastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoast.CubeDataRow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("Qin")
                        .HasColumnType("float");

                    b.Property<float>("Qout")
                        .HasColumnType("float");

                    b.Property<int>("basinID")
                        .HasColumnType("int");

                    b.Property<float>("burn")
                        .HasColumnType("float");

                    b.Property<float>("canopyevap")
                        .HasColumnType("float");

                    b.Property<float>("consumedCOver")
                        .HasColumnType("float");

                    b.Property<float>("consumedCUnder")
                        .HasColumnType("float");

                    b.Property<float>("coverfract")
                        .HasColumnType("float");

                    b.Property<int>("dateIdx")
                        .HasColumnType("int");

                    b.Property<float>("depthToGW")
                        .HasColumnType("float");

                    b.Property<float>("groundevap")
                        .HasColumnType("float");

                    b.Property<float>("heightOver")
                        .HasColumnType("float");

                    b.Property<float>("heightUnder")
                        .HasColumnType("float");

                    b.Property<int>("hillID")
                        .HasColumnType("int");

                    b.Property<int>("importRunId")
                        .HasColumnType("int");

                    b.Property<float>("laiOver")
                        .HasColumnType("float");

                    b.Property<float>("laiUnder")
                        .HasColumnType("float");

                    b.Property<float>("leafCOver")
                        .HasColumnType("float");

                    b.Property<float>("leafCUnder")
                        .HasColumnType("float");

                    b.Property<float>("litterc")
                        .HasColumnType("float");

                    b.Property<float>("mortCOver")
                        .HasColumnType("float");

                    b.Property<float>("mortCUnder")
                        .HasColumnType("float");

                    b.Property<float>("netpsnOver")
                        .HasColumnType("float");

                    b.Property<float>("netpsnUnder")
                        .HasColumnType("float");

                    b.Property<long>("patchID")
                        .HasColumnType("bigint");

                    b.Property<float>("rain")
                        .HasColumnType("float");

                    b.Property<float>("rootCOver")
                        .HasColumnType("float");

                    b.Property<float>("rootCUnder")
                        .HasColumnType("float");

                    b.Property<float>("rootdepth")
                        .HasColumnType("float");

                    b.Property<float>("rootdepthCOver")
                        .HasColumnType("float");

                    b.Property<float>("rootdepthUnder")
                        .HasColumnType("float");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float>("soilc")
                        .HasColumnType("float");

                    b.Property<float>("stemCOver")
                        .HasColumnType("float");

                    b.Property<float>("stemCUnder")
                        .HasColumnType("float");

                    b.Property<long>("stratumIDOver")
                        .HasColumnType("bigint");

                    b.Property<long>("stratumIDUnder")
                        .HasColumnType("bigint");

                    b.Property<float>("streamflow")
                        .HasColumnType("float");

                    b.Property<float>("transOver")
                        .HasColumnType("float");

                    b.Property<float>("transUnder")
                        .HasColumnType("float");

                    b.Property<float>("vegAccessWater")
                        .HasColumnType("float");

                    b.Property<int>("vegParmIDOver")
                        .HasColumnType("int");

                    b.Property<int>("vegParmIDUnder")
                        .HasColumnType("int");

                    b.Property<int>("warmingIdx")
                        .HasColumnType("int");

                    b.Property<int>("zoneID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scenarioRunId", "warmingIdx", "dateIdx", "zoneID", "patchID");

                    b.ToTable("CubeData");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoast.BurnDataRow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("basinID")
                        .HasColumnType("int");

                    b.Property<float>("burn")
                        .HasColumnType("float");

                    b.Property<int?>("hillID")
                        .HasColumnType("int");

                    b.Property<int>("importRunId")
                        .HasColumnType("int");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<long?>("patchID")
                        .HasColumnType("bigint");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sourceFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("warmingIdx")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.Property<int?>("zoneID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scenarioRunId", "warmingIdx", "year", "month", "zoneID", "patchID");

                    b.ToTable("BurnData");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoast.ImportRun", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("databaseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("filesImported")
                        .HasColumnType("int");

                    b.Property<DateTime?>("finishedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("rowsImported")
                        .HasColumnType("bigint");

                    b.Property<string>("scenarioName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("scenarioProfile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sourceRoot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("startedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("warmingIdx")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ImportRun");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoast.PatchDataRow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("importRunId")
                        .HasColumnType("int");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("zoneID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scenarioRunId", "zoneID");

                    b.ToTable("PatchData");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoast.StratumDataRow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("basinID")
                        .HasColumnType("int");

                    b.Property<int>("hillID")
                        .HasColumnType("int");

                    b.Property<int>("importRunId")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<long>("patchID")
                        .HasColumnType("bigint");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sourceFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("stratumID")
                        .HasColumnType("bigint");

                    b.Property<float>("total_plantc")
                        .HasColumnType("float");

                    b.Property<float>("totalc")
                        .HasColumnType("float");

                    b.Property<int>("warmingIdx")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.Property<int>("zoneID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scenarioRunId", "warmingIdx", "year", "month", "stratumID");

                    b.ToTable("StratumData");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoast.TerrainDataRow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("_dataList")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("decimalPrecision")
                        .HasColumnType("int");

                    b.Property<int>("gridHeight")
                        .HasColumnType("int");

                    b.Property<int>("gridSize")
                        .HasColumnType("int");

                    b.Property<int>("gridWidth")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<int>("pixelGrainSize")
                        .HasColumnType("int");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("warmingIdx")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scenarioRunId", "warmingIdx", "year", "month");

                    b.ToTable("TerrainData");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.CentralCoast.WaterDataRow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("basinID")
                        .HasColumnType("int");

                    b.Property<float>("burn")
                        .HasColumnType("float");

                    b.Property<float>("cs_dead_crootc")
                        .HasColumnType("float");

                    b.Property<float>("cs_dead_stemc")
                        .HasColumnType("float");

                    b.Property<float>("cs_frootc")
                        .HasColumnType("float");

                    b.Property<float>("cs_leafc")
                        .HasColumnType("float");

                    b.Property<float>("cs_leafc_store")
                        .HasColumnType("float");

                    b.Property<float>("cs_live_crootc")
                        .HasColumnType("float");

                    b.Property<float>("cs_live_stemc")
                        .HasColumnType("float");

                    b.Property<float>("cs_net_psn")
                        .HasColumnType("float");

                    b.Property<int>("dateIdx")
                        .HasColumnType("int");

                    b.Property<float>("epv_height")
                        .HasColumnType("float");

                    b.Property<float>("evaporation")
                        .HasColumnType("float");

                    b.Property<float>("evaporation_surf")
                        .HasColumnType("float");

                    b.Property<float>("exfiltration_sat_zone")
                        .HasColumnType("float");

                    b.Property<float>("exfiltration_unsat_zone")
                        .HasColumnType("float");

                    b.Property<float>("family_pct_cover")
                        .HasColumnType("float");

                    b.Property<float>("fe_canopy_target_prop_c_consumed")
                        .HasColumnType("float");

                    b.Property<float>("fe_canopy_target_prop_c_remain_adjusted")
                        .HasColumnType("float");

                    b.Property<float>("fe_canopy_target_prop_c_remain_adjusted_leafc")
                        .HasColumnType("float");

                    b.Property<int>("importRunId")
                        .HasColumnType("int");

                    b.Property<float>("litter_cs_totalc")
                        .HasColumnType("float");

                    b.Property<float>("rain")
                        .HasColumnType("float");

                    b.Property<float>("rootzone_depth")
                        .HasColumnType("float");

                    b.Property<float>("rz_storage")
                        .HasColumnType("float");

                    b.Property<float>("sat_deficit_z")
                        .HasColumnType("float");

                    b.Property<string>("scenarioRunId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float>("soil_cs_totalc")
                        .HasColumnType("float");

                    b.Property<float>("streamflow")
                        .HasColumnType("float");

                    b.Property<float>("transpiration_sat_zone")
                        .HasColumnType("float");

                    b.Property<float>("transpiration_unsat_zone")
                        .HasColumnType("float");

                    b.Property<int>("warmingIdx")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scenarioRunId", "warmingIdx", "dateIdx");

                    b.ToTable("WaterData");
                });

            modelBuilder.Entity("RHESSYs_Data_Importer.Models.Date", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Dates");
                });
#pragma warning restore 612, 618
        }
    }
}
